// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-season-standings.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
import { pastStandings, pastTeamStandings } from "npm:@/data/corefallData";
var get_season_standings_default = defineTool({
  name: "get_season_standings",
  title: "Get season standings",
  description: "Return the player standings (rank, name, team, age, points, KOs) and the team standings for a given Corefall season year.",
  inputSchema: {
    year: z.union([z.string(), z.number()]).describe("Season year, e.g. 712. Modern seasons run from 700 onwards."),
    limit: z.number().int().min(1).max(200).optional().describe("Max number of players to return. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ year, limit }) => {
    const key = String(year);
    const players = pastStandings[key];
    if (!players) {
      throw new ToolError(
        `No standings for season ${key}. Available seasons: ${Object.keys(pastStandings).sort().join(", ")}`
      );
    }
    const teams = pastTeamStandings[key] ?? [];
    const top = players.slice(0, limit ?? 25);
    const payload = { year: Number(key), players: top, teamStandings: teams };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-players.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
import { pastStandings as pastStandings2, apexDetailed } from "npm:@/data/corefallData";
var search_players_default = defineTool2({
  name: "search_players",
  title: "Search players",
  description: "Search Corefall fighters by (partial) name across every recorded season. Returns each match with their most recent team, age, seasons competed, and total career points.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Full or partial fighter name."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results, defaults to 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    const acc = /* @__PURE__ */ new Map();
    for (const [yearKey, rows] of Object.entries(pastStandings2)) {
      const year = Number(yearKey);
      for (const row of rows) {
        if (!row.Name.toLowerCase().includes(q)) continue;
        const entry = acc.get(row.Name) ?? {
          name: row.Name,
          latestTeam: row.Team,
          latestAge: row.Age,
          latestSeason: year,
          seasons: [],
          totalPoints: 0
        };
        entry.seasons.push(year);
        entry.totalPoints += row.Points ?? 0;
        if (year >= entry.latestSeason) {
          entry.latestSeason = year;
          entry.latestTeam = row.Team;
          entry.latestAge = row.Age;
        }
        acc.set(row.Name, entry);
      }
    }
    for (const final of apexDetailed) {
      for (const [name, team] of [
        [final.win, final.wTeam],
        [final.lose, final.lTeam]
      ]) {
        if (!name?.toLowerCase().includes(q) || acc.has(name)) continue;
        acc.set(name, {
          name,
          latestTeam: team,
          latestAge: 0,
          latestSeason: final.year,
          seasons: [final.year],
          totalPoints: 0
        });
      }
    }
    const results = [...acc.values()].map((r) => ({ ...r, seasons: [...new Set(r.seasons)].sort((a, b) => b - a) })).sort((a, b) => b.totalPoints - a.totalPoints).slice(0, limit ?? 15);
    const payload = { query, count: results.length, results };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-player-profile.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
import { pastStandings as pastStandings3, trophyData, apexDetailed as apexDetailed2, majorWinners } from "npm:@/data/corefallData";
import { rosterMoves } from "npm:@/data/rosterMoves";
var get_player_profile_default = defineTool3({
  name: "get_player_profile",
  title: "Get player profile",
  description: "Full career profile for one Corefall fighter: season-by-season standings, trophy haul, Apex finals appearances, major wins, and roster moves.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Fighter's full name, e.g. 'Daredevil Gaffe'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name }) => {
    const q = name.toLowerCase();
    const seasonResults = Object.entries(pastStandings3).flatMap(
      ([year, rows]) => rows.filter((r) => r.Name.toLowerCase() === q || r.Name.toLowerCase().includes(q)).map((r) => ({ season: Number(year), rank: r.Rank, team: r.Team, age: r.Age, points: r.Points, kos: r.KOs }))
    ).sort((a, b) => b.season - a.season);
    const trophies = trophyData.find(
      (t) => t.name.toLowerCase() === q || t.name.toLowerCase().includes(q)
    );
    const apexFinals = apexDetailed2.filter((a) => a.win?.toLowerCase().includes(q) || a.lose?.toLowerCase().includes(q)).map((a) => ({
      year: a.year,
      result: a.win?.toLowerCase().includes(q) ? "won" : "runner-up",
      opponent: a.win?.toLowerCase().includes(q) ? a.lose : a.win
    }));
    const majors = majorWinners.filter((m) => m.winner.toLowerCase().includes(q)).map((m) => ({ year: m.year, tournament: m.tournament }));
    const moves = rosterMoves.filter((m) => m.player.toLowerCase().includes(q));
    if (!seasonResults.length && !trophies && !apexFinals.length && !majors.length) {
      throw new ToolError2(`No Corefall fighter found matching "${name}". Try the search_players tool.`);
    }
    const payload = {
      name: trophies?.name ?? name,
      trophies: trophies ?? null,
      apexFinals,
      majorWins: majors,
      seasonResults,
      rosterMoves: moves
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-season-history.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
import { seasons, apexDetailed as apexDetailed3, majorWinners as majorWinners2 } from "npm:@/data/corefallData";
var get_season_history_default = defineTool4({
  name: "get_season_history",
  title: "Get season history",
  description: "Corefall season history: Apex champion, Apex finals matchup, CTT-winning team, Season Star, and every major winner for each season.",
  inputSchema: {
    fromYear: z4.number().int().optional().describe("Earliest season year to include (inclusive)."),
    toYear: z4.number().int().optional().describe("Latest season year to include (inclusive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ fromYear, toYear }) => {
    const lo = fromYear ?? -Infinity;
    const hi = toYear ?? Infinity;
    const results = seasons.filter((s) => s.year >= lo && s.year <= hi).map((s) => {
      const final = apexDetailed3.find((a) => a.year === s.year);
      return {
        year: s.year,
        apexChampion: s.apex,
        apexChampionTeam: s.team,
        apexRunnerUp: final?.lose ?? null,
        apexRunnerUpTeam: final?.lTeam ?? null,
        cttChampionTeam: s.ctt,
        seasonStar: s.star,
        seasonStarTeam: s.starTeam,
        majorWinners: majorWinners2.filter((m) => m.year === s.year).map((m) => ({ tournament: m.tournament, winner: m.winner }))
      };
    }).sort((a, b) => b.year - a.year);
    const payload = { count: results.length, seasons: results };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-roster-moves.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
import { rosterMoves as rosterMoves2 } from "npm:@/data/rosterMoves";
var get_roster_moves_default = defineTool5({
  name: "get_roster_moves",
  title: "Get roster moves",
  description: "List Corefall transfers/roster moves, optionally filtered by season, player, or team (old or new).",
  inputSchema: {
    season: z5.union([z5.string(), z5.number()]).optional().describe("Season year, e.g. 712."),
    player: z5.string().trim().optional().describe("Filter by fighter name (partial match)."),
    team: z5.string().trim().optional().describe("Filter by team, matching either the old or new team.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ season, player, team }) => {
    const p = player?.toLowerCase();
    const t = team?.toLowerCase();
    const s = season !== void 0 ? String(season) : void 0;
    const results = rosterMoves2.filter((m) => {
      if (s && String(m.season) !== s) return false;
      if (p && !m.player.toLowerCase().includes(p)) return false;
      if (t && !`${m.oldTeam} ${m.newTeam}`.toLowerCase().includes(t)) return false;
      return true;
    });
    const payload = { count: results.length, moves: results };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-fan-lists.ts
import { defineTool as defineTool6, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-fan-lists.ts
var list_fan_lists_default = defineTool6({
  name: "list_fan_lists",
  title: "List fan-voted lists",
  description: "List the in-universe fan-voted Corefall lists published in the archive, with their ranked entries.",
  inputSchema: {
    search: z6.string().trim().optional().describe("Filter lists whose name contains this text."),
    limit: z6.number().int().min(1).max(50).optional().describe("Max lists to return, defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("fan_lists").select("id, name, description, items, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    const payload = { count: data?.length ?? 0, lists: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "corefall-news",
  title: "Corefall News",
  version: "0.1.0",
  instructions: "Tools for Corefall News, an archive of the Corefall esports scene. Use `search_players` to resolve a fighter name, `get_player_profile` for a full career breakdown, `get_season_standings` for a season's player and team tables, `get_season_history` for Apex/CTT/Season Star and major winners, `get_roster_moves` for transfers, and `list_fan_lists` for published fan-voted lists. All data is public.",
  tools: [
    search_players_default,
    get_player_profile_default,
    get_season_standings_default,
    get_season_history_default,
    get_roster_moves_default,
    list_fan_lists_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
